const dotenv = require('dotenv').config();

module.exports = {
	DATABASE_URL: process.env.CHAINFUNDIT_URI,

	PAYSTACK_SECRET_KEY: process.env.PAYSTACK_SECRET_KEY,

	STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,

	CHAINFOUNDATION_PAYPAL_SECRET_KEY:
		process.env.CHAINFOUNDATION_PAYPAL_SECRET_KEY,

	CHAINFOUNDATION_PAYPAL_CLIENT_ID:
		process.env.CHAINFOUNDATION_PAYPAL_CLIENT_ID,

	CHAINFOUNDATION_PAYPAL_ACCESS_TOKEN:
		process.env.CHAINFOUNDATION_PAYPAL_ACCESS_TOKEN,
};
